version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:  
      - "5437:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  flight-booking:
    image: app
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
      - redis
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
