port: "8080"

db:
  host: "localhost"
  port: "5437"
  username: "postgres"
  password: "password"
  dbname: "postgres"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 1